add volta-cli

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,18 +10,24 @@ permissions:
   actions: read
   contents: read
 
+env:
+  NX_BRANCH: ${{ github.event.number || github.ref_name }}
+
 jobs:
   main:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+      # Set node/npm/yarn versions using volta
+      - uses: volta-cli/action@v4
+        with:
+          package-json-path: '${{ github.workspace }}/package.json'
       - uses: actions/setup-node@v4
         with:
           node-version: 20
           cache: 'npm'
 
       - run: npm ci
-      - run: npx playwright install --with-deps
       - uses: nrwl/nx-set-shas@v4
 
       - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"
@@ -30,24 +36,27 @@ jobs:
           # initialize an array to store process IDs (PIDs)
           pids=()
 
-          # function to run commands and store the PIDs
+          # function to run commands and store the PID
           function run_command() {
             local command=$1
-            $command & # run the command in the background
-            pids+=($!) # store the PID of the background process
+            $command &  # run the command in the background
+            pids+=($!)  # store the PID of the background process
           }
 
+          # list of commands to be run on main has env flag NX_CLOUD_DISTRIBUTED_EXECUTION set to false
+          run_command "NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx-cloud record -- nx format:check"
+
           # list of commands to be run on agents
-          run_command "npx nx affected -t lint test build e2e"
+          run_command "npx nx affected -t lint,test,build,e2e-ci --parallel=3"
 
           # wait for all background processes to finish
           for pid in ${pids[*]}; do
             if ! wait $pid; then
-              exit 1 # exit with an error status if any process fails
+              exit 1  # exit with an error status if any process fails
             fi
           done
 
-          exit 0 # exists with success status if all processes complete successfully
+          exit 0 # exits with success status if a all processes complete successfully
   agents:
     name: Agent ${{ matrix.agent }}
     runs-on: ubuntu-latest
@@ -56,7 +65,11 @@ jobs:
         agent: [1, 2, 3]
     steps:
       - name: Checkout
-        uses: actions/checkout@v4 
+        uses: actions/checkout@v4
+      
+      - uses: volta-cli/action@v4
+        with:
+          package-json-path: '${{ github.workspace }}/package.json'
       
       - name: Use the package manager cache if available
         uses: actions/setup-node@v3
